/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.hsrw.ci_2_04_programming;

public class App {
    public static void main(String[] args) {
		HelloTime a = new HelloTime("Ford Perfect");
		HelloTime b = new HelloTime("Arthur Dent");
		HelloTime c = new HelloTime("Marvin");
		System.out.println(a.greet());
		System.out.println(b.greet());
		System.out.println(c.greet());
    }
}
